@push('head:styles')
    <link rel="stylesheet" href="{{ asset('css/vendor/tagify.css') }}">
    <link rel="stylesheet" href="{{ asset('css/vendor/easymde.css') }}">
@endpush

@push('scripts')
    <script src="{{ asset('js/vendor/tagify.js') }}" defer></script>
    <script src="{{ asset('js/vendor/easymde.js') }}" defer></script>
@endpush

<div>

    <form wire:submit.prevent="save">

        <div class="max-w-2xl pt-10 mx-4 space-y-10 lg:mx-auto">

            <h1 class="text-5xl font-black text-center text-gray-700">
                Create Blog Post
            </h1>
        
        </div>
        
        <div class="max-w-2xl mx-4 mt-10 mb-16 lg:mx-auto">
        
            <label for="title" class="flex flex-col mt-8 space-y-2">
        
                <span class="inline-flex font-semibold">
                    Post Title
                </span>
                
                <input type="text" id="title" name="title" wire:model="post.title" placeholder="Your post title" class="rounded-sm focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-purple-500 focus:ring-offset-purple-200 focus:border-gray-300" autocomplete="off" spellcheck="false" required>
        
                <x-errors.inline key="post.title" />
        
            </label>
        
            <label for="slug" class="flex flex-col mt-8 space-y-2">
        
                <span class="inline-flex font-semibold">
                    Post Slug
                </span>
                
                <input type="text" id="slug" name="slug" wire:model="post.slug" placeholder="This will be autogenerated" class="border-gray-400 rounded-sm focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-purple-500 focus:ring-offset-purple-200 focus:border-gray-300" autocomplete="off" spellcheck="false" required readonly disabled>
        
                <x-errors.inline key="post.slug" />
        
            </label>
        
            <label for="tags" class="flex flex-col mt-8 space-y-2">
        
                <span class="inline-flex font-semibold">
                    Post Tags
                </span>
                
                <div x-cloak wire:ignore x-data="{ tagify: null }" class="w-full" "> <!-- x-init="tagify = new Tagify($refs['tag-input']); -->
                    <input type="text" id="tag-input" name="tags" wire:model="tags" placeholder="Add or select some tags" class="w-full border-gray-400 rounded-sm focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-purple-500 focus:ring-offset-purple-200 focus:border-gray-300">
                </div>
        
                <x-errors.inline key="tags" />

                @push('scripts')
                    <script>
                        document.addEventListener("livewire:load", function(event) {
                            
                            var input = document.getElementById('tag-input')
                            
                            var tagify = new Tagify(input, {
                                whitelist : [
                                    @foreach($allTags as $tag)
                                        '{{ $tag->name }}',
                                    @endforeach
                                ]                            
                            });
                            
                            input.addEventListener('change', function(event) {
                                @this.call('changeTags', event.target.value)
                            });

                        });
                    </script>
                @endpush
        
            </label>     

            <label for="excerpt" class="flex flex-col mt-8 space-y-2">
        
                <span class="inline-flex font-semibold">
                    Post Excerpt
                </span>
                
                <textarea id="excerpt" name="excerpt" wire:model.defer="post.excerpt" placeholder="A quick recap of what this post is about, 240 chars or less" class="border-gray-400 rounded-sm focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-purple-500 focus:ring-offset-purple-200 focus:border-gray-300"></textarea>
        
                <x-errors.inline key="post.excerpt" />
        
            </label>     
            
            <label for="post.content" class="flex flex-col mt-8 space-y-2">
        
                <span class="inline-flex font-semibold">
                    Post Content
                </span>
                
                <div wire:ignore>

                    <textarea name="post.content" id="content" wire:model="post.content"></textarea>
                    
                </div>
        
                <x-errors.inline key="post.content" />
        
            </label>

            @push('scripts')
                
                <script>
                    
                    document.addEventListener("livewire:load", function() {

                        window.easyMDE = new EasyMDE({ 
                            element: document.querySelector("#content"), ... {
                                'minHeight': '300px',
                                'forceSync': true,
                                'previewClass': 'prose prose-purple bg-white p-10 max-w-none z-50',
                                'autoDownloadFontAwesome': true,
                                'uploadImage': true,
                                'imageMaxSize': (1024 * 1024 * 5),
                                'imageUploadEndpoint': '{{ route('posts.media.upload') }}',
                                'status': false,
                            }})

                        window.easyMDE.codemirror.on('change', function () {
                            @this.set('post.content', window.easyMDE.value())
                        });     
                        
                    })

                </script>

            @endpush
        
        </div>

        <div>
            <button type="submit">Save Post</button>
        </div>

    </form>

</div>